# Generated by Django 5.2.6 on 2026-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL (на английском)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.TextField(verbose_name='Название контента'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(verbose_name='Название контента'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.TextField(verbose_name='Название контента'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(verbose_name='Название контента'),
        ),
    ]
