"""
Django settings for education project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# БАЗОВЫЕ НАСТРОЙКИ
# ============================================================================

# Попробуем загрузить .env файл для локальной разработки
try:
    from dotenv import load_dotenv
    load_dotenv()
    print("✅ .env file loaded for local development")
except ImportError:
    # dotenv не установлен - нормально для продакшена
    pass

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-ваш-ключ-только-для-локальной-разработки'  # Меняйте локально
)

# SECURITY WARNING: don't run with debug turned on in production!
# Определяем DEBUG автоматически:
# - На Render: DEBUG=False (если нет переменной DEBUG)
# - Локально: DEBUG=True (по умолчанию)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ============================================================================
# РАЗРЕШЕННЫЕ ХОСТЫ
# ============================================================================

ALLOWED_HOSTS = []

# Автоматически добавляем домен Render при деплое
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    print(f"✅ Added Render hostname: {RENDER_EXTERNAL_HOSTNAME}")

# Для локальной разработки всегда разрешаем localhost
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '[::1]'])
    print("✅ DEBUG mode enabled - local hosts allowed")

# ============================================================================
# БАЗА ДАННЫХ
# ============================================================================

# По умолчанию используем SQLite (для локальной разработки)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Если есть DATABASE_URL (на Render) - используем PostgreSQL
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(
            DATABASE_URL, 
            conn_max_age=600, 
            ssl_require=True
        )
        print("✅ PostgreSQL database configured from DATABASE_URL")
    except ImportError:
        print("⚠️ dj-database-url not installed, using SQLite")
    except Exception as e:
        print(f"⚠️ Error configuring database: {e}")
else:
    print("✅ Using SQLite database for local development")

# ============================================================================
# APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    'students.apps.StudentsConfig',
    'courses.apps.CoursesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Для статики на Render
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Важно: после SecurityMiddleware!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'education.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'education.wsgi.application'

# ============================================================================
# ПАРОЛЬНАЯ ВАЛИДАЦИЯ
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# МЕЖДУНАРОДНЫЕ НАСТРОЙКИ
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (CSS, JavaScript, Images)
# ============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================================================
# БЕЗОПАСНОСТЬ ДЛЯ ПРОДАКШЕНА (только на Render)
# ============================================================================

if not DEBUG and RENDER_EXTERNAL_HOSTNAME:
    # HTTPS настройки
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']
    
    print("✅ Production security settings enabled")
else:
    # Локальные настройки безопасности
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    print("✅ Development security settings enabled")

# ============================================================================
# ОСТАЛЬНЫЕ НАСТРОЙКИ
# ============================================================================

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login redirect
LOGIN_REDIRECT_URL = reverse_lazy('profile')

# Media files (загруженные файлы)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# ============================================================================
# ПРЕДУПРЕЖДЕНИЕ ДЛЯ ПРОДАКШЕНА
# ============================================================================

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    print("""
    ⚠️  ВНИМАНИЕ! Вы используете дефолтный SECRET_KEY на продакшене!
    Это небезопасно. На Render добавьте переменную окружения:
    
    Key: SECRET_KEY
    Value: [сгенерируйте новый ключ: python -c "import secrets; print(secrets.token_urlsafe(50))"]
    """)

print(f"✅ Settings loaded: DEBUG={DEBUG}, Database={DATABASES['default']['ENGINE']}")